<script lang="ts">
  import { goto } from '$app/navigation';

  function goHome() {
    goto('/');
  }
</script>

<h1 class="text-3xl md:text-4xl font-extrabold text-gray-800 text-center mb-8">
  Terms & Conditions
</h1>

<div class="max-w-2xl mx-auto text-gray-700 leading-relaxed space-y-6">
  <p>
    By using <strong>Paste Pal 📋</strong>, you agree to the following terms:
  </p>

  <ul class="list-disc list-inside space-y-2">
    <li>All content shared in rooms is generated by users. We do not moderate or review content.</li>
    <li>Rooms are temporary and may be deleted automatically after a period of inactivity.</li>
    <li>You are responsible for any data you share. Do not share sensitive or illegal content.</li>
    <li>We do not guarantee uninterrupted access, availability, or permanent storage of your data.</li>
  </ul>

  <p>
    These terms may be updated over time. Continued use of the service means you agree to any updates.
  </p>

  <button
    class="mt-6 px-5 py-3 rounded-xl bg-blue-600 text-white font-semibold shadow hover:bg-blue-700 active:scale-[0.98] transition"
    on:click={goHome}
  >
    Back to Home
  </button>
</div>
